name: Keboola Component Build & Deploy Pipeline
on:
  push:
    branches-ignore:
      - main
    tags:
      - "*"

concurrency: ci-${{ github.ref }}

jobs:
  ci:
    uses: keboola/component-ci/.github/workflows/component-pipeline.yml@master
    with:
      app_id: "kds-team.wr-hubspot"
      vendor: "kds-team"
      kbc_developerportal_username: "kds-team+github"
      test_build_target: "test"
      docker_build_target: "production"
    secrets: inherit
